# Generated by Django 5.2.7 on 2025-12-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Conte um pouco sobre você (máx. 500 caracteres)', max_length=500, null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Imagem JPG ou PNG até 5MB', null=True, upload_to='perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nome_usuario',
            field=models.CharField(blank=True, help_text='Apelido público (ex: @investidor_top)', max_length=50, null=True, unique=True, verbose_name='Nome de Usuário'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Email usado para login', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
