# Generated by Django 5.2.7 on 2025-12-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_profile_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Conte um pouco sobre você (máximo 500 caracteres)', max_length=500, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Imagem de perfil (max 5MB)', null=True, upload_to='perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome_completo',
            field=models.CharField(blank=True, help_text='Seu nome completo', max_length=150, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome_usuario',
            field=models.CharField(blank=True, help_text='Nome público para rankings e identificação (ex: @investidor_top)', max_length=50, null=True, unique=True, verbose_name='Nome de Usuário'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número de telefone para contato', max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
