# Generated by Django 5.2.7 on 2025-11-25 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0002_category_categories__user_id_f0c68e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Limite de Orçamento')),
                ('month', models.IntegerField(help_text='Mês do orçamento (1-12)', verbose_name='Mês')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('is_general', models.BooleanField(default=False, help_text='Aplica a todas as categorias', verbose_name='Orçamento Geral')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(blank=True, help_text='Deixe em branco para orçamento geral', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['user', 'month', 'year'], name='accounts_bu_user_id_0f9f95_idx'), models.Index(fields=['category', 'month', 'year'], name='accounts_bu_categor_e379a0_idx')],
                'unique_together': {('user', 'category', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cartão')),
                ('card_number', models.CharField(help_text='Apenas os 4 últimos dígitos do cartão', max_length=4, verbose_name='Últimos 4 dígitos')),
                ('card_brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('amex', 'American Express'), ('hipercard', 'Hipercard'), ('other', 'Outro')], default='visa', max_length=20, verbose_name='Bandeira')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Limite de Crédito')),
                ('closing_day', models.IntegerField(help_text='Dia do mês (1-28)', verbose_name='Dia de Fechamento')),
                ('due_day', models.IntegerField(help_text='Dia do mês (1-28)', verbose_name='Dia de Vencimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='accounts.account', verbose_name='Conta Vinculada')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['account', 'is_active'], name='accounts_cr_account_92dc45_idx'), models.Index(fields=['-created_at'], name='accounts_cr_created_7cfc59_idx')],
            },
        ),
    ]
