# Generated by Django 5.2.7 on 2025-11-25 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_budget_creditcard'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, help_text='Vincule se a transação foi feita com cartão de crédito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.creditcard', verbose_name='Cartão de Crédito'),
        ),
    ]
