# Generated by Django 5.2.7 on 2025-11-26 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome/apelido do cartão', max_length=100)),
                ('banco', models.CharField(choices=[('nubank', 'Nubank'), ('inter', 'Inter'), ('c6', 'C6 Bank'), ('neon', 'Neon'), ('picpay', 'PicPay'), ('itau', 'Itaú'), ('bradesco', 'Bradesco'), ('santander', 'Santander'), ('bb', 'Banco do Brasil'), ('caixa', 'Caixa'), ('outros', 'Outros')], default='outros', max_length=50)),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('american_express', 'American Express'), ('hipercard', 'Hipercard'), ('outros', 'Outros')], default='visa', max_length=50)),
                ('ultimos_digitos', models.CharField(help_text='Últimos 4 dígitos', max_length=4)),
                ('limite_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_fechamento', models.IntegerField(help_text='Dia do fechamento da fatura (1-31)')),
                ('dia_vencimento', models.IntegerField(help_text='Dia do vencimento da fatura (1-31)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='cards.conta')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_fechamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('paga', 'Paga'), ('atrasada', 'Atrasada')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='cards.cartao')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('cartao', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='TransacaoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('compras', 'Compras'), ('outros', 'Outros')], default='outros', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('parcelas', models.IntegerField(default=1)),
                ('parcela_atual', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='cards.cartao')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='cards.fatura')),
            ],
            options={
                'verbose_name': 'Transação de Cartão',
                'verbose_name_plural': 'Transações de Cartão',
                'ordering': ['-data'],
            },
        ),
    ]
