# Generated by Django 5.2.7 on 2025-11-26 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_budget_creditcard'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='accounts.account'),
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
    ]
