# Generated by Django 5.2.7 on 2025-12-04 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('rara', 'Rara'), ('epica', 'Épica'), ('lendaria', 'Lendária')], default='comum', max_length=20)),
                ('pontos', models.IntegerField(default=10)),
                ('icone', models.CharField(max_length=50)),
                ('condicao', models.CharField(help_text='Condição para desbloquear', max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('meta_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meta_quantidade', models.IntegerField(blank=True, null=True)),
                ('meta_dias_consecutivos', models.IntegerField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Conquistas',
                'ordering': ['tipo', 'raridade', 'pontos'],
            },
        ),
        migrations.CreateModel(
            name='NivelFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 'Aprendiz Financeiro'), (2, 'Organizador Consciente'), (3, 'Poupador Estratégico'), (4, 'Investidor Iniciante'), (5, 'Mestre das Finanças')], unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('pontos_necessarios', models.IntegerField()),
                ('icone', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#D4AF37', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Níveis Financeiros',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('geral', 'Geral')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('top_usuarios', models.JSONField(default=dict, help_text='Top 10 usuários do período')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoConquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('economia', 'Economia'), ('organizacao', 'Organização'), ('investimento', 'Investimento'), ('quitacao', 'Quitação de Dívidas'), ('disciplina', 'Disciplina'), ('conhecimento', 'Conhecimento Financeiro')], max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('periodo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('personalizado', 'Personalizado')], max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='ativo', max_length=20)),
                ('pontos_recompensa', models.IntegerField(default=50)),
                ('meta_tipo', models.CharField(help_text='economia, reduzir_gastos, etc', max_length=50)),
                ('meta_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meta_percentual', models.IntegerField(blank=True, help_text='Para redução de gastos', null=True)),
                ('meta_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('participantes_minimos', models.IntegerField(default=1)),
                ('publico', models.BooleanField(default=True, help_text='Visível para todos os usuários')),
                ('conquista_recompensa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desafios', to='gamification.conquista')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_totais', models.IntegerField(default=0)),
                ('streak_atual', models.IntegerField(default=0, help_text='Dias consecutivos de registro')),
                ('maior_streak', models.IntegerField(default=0)),
                ('ultima_atividade', models.DateField(blank=True, null=True)),
                ('conquistas_desbloqueadas', models.IntegerField(default=0)),
                ('desafios_completados', models.IntegerField(default=0)),
                ('notificacoes_gamificacao', models.BooleanField(default=True)),
                ('exibir_ranking', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nivel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.nivelfinanceiro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Gamificação',
                'verbose_name_plural': 'Perfis de Gamificação',
            },
        ),
        migrations.CreateModel(
            name='HistoricoGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pontos', 'Pontos Ganhos'), ('conquista', 'Conquista Desbloqueada'), ('nivel_up', 'Subiu de Nível'), ('desafio', 'Desafio Completado'), ('streak', 'Streak Mantido')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('pontos', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='gamification.perfilgamificacao')),
            ],
            options={
                'verbose_name': 'Histórico de Gamificação',
                'verbose_name_plural': 'Históricos de Gamificação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='conquista',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='gamification.tipoconquista'),
        ),
        migrations.CreateModel(
            name='DesafioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('completado', 'Completado'), ('falhado', 'Falhado'), ('desistiu', 'Desistiu')], default='em_andamento', max_length=20)),
                ('progresso', models.IntegerField(default=0, help_text='Progresso em percentual')),
                ('valor_alcancado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('completado_em', models.DateTimeField(blank=True, null=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='gamification.desafio')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='gamification.perfilgamificacao')),
            ],
            options={
                'verbose_name': 'Desafio do Usuário',
                'verbose_name_plural': 'Desafios dos Usuários',
                'ordering': ['-iniciado_em'],
                'unique_together': {('perfil', 'desafio')},
            },
        ),
        migrations.CreateModel(
            name='ConquistaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueada_em', models.DateTimeField(auto_now_add=True)),
                ('visualizada', models.BooleanField(default=False)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.conquista')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='gamification.perfilgamificacao')),
            ],
            options={
                'verbose_name': 'Conquista do Usuário',
                'verbose_name_plural': 'Conquistas dos Usuários',
                'ordering': ['-desbloqueada_em'],
                'unique_together': {('perfil', 'conquista')},
            },
        ),
    ]
