# Generated by Django 5.2.7 on 2025-12-05 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
         migrations.AddField(
            model_name='conquista',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, default='temp'),
            preserve_default=False,
        ),
    ]
