# Generated by Django 5.2.7 on 2025-12-05 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_conquista_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conquista',
            name='codigo',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
