# Generated by Django 5.2.7 on 2025-12-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_conquista_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilgamificacao',
            name='apelido',
            field=models.CharField(blank=True, help_text='Apelido público do usuário (ex: Rápido Leão)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilgamificacao',
            name='exibir_nome_real',
            field=models.BooleanField(default=False, help_text='Se marcado, exibe o email no ranking. Caso contrário, usa apelido anônimo.'),
        ),
        migrations.AddField(
            model_name='perfilgamificacao',
            name='perfil_publico',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o perfil não aparece em rankings públicos'),
        ),
    ]
